controller_manager:
  ros__parameters:
    update_rate: 10  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    mecanum_controller:
      type: mecanum_controller/MecanumController


mecanum_controller:
  ros__parameters:
    distance_left_to_right_wheel: 10.0
    distance_front_to_rear_wheel: 7.5
    wheel_radius: 3.0
    front_left_joint: "Joint_FrontLeft"
    front_right_joint: "Joint_FrontRight"
    back_left_joint: "Joint_BackLeft"
    back_right_joint: "Joint_BackRight"


