controller_manager:
  ros__parameters:
    update_rate: 10  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    velocity_controller:
      type: velocity_controllers/JointGroupVelocityController


velocity_controller:
  ros__parameters:
    joints:
      - Joint_BackLeft
      - Joint_BackRight
      - Joint_FrontRight
      - Joint_FrontLeft


